### ISSUE TITLE
single_task_coder.py fails

### ISSUE THREAD

**Issue by radekrepo** [Grigorij-Dudnik/Clean-Coder-AI#28]
**python .\single_task_coder.py**

            +                                                      +
           +++                                                    +++
          +  ++                                                 + ++++
         +++ + ++                                       +    +++ ++  +
          +++   +++   +                                ++ ++++  + ++++
          +++++   +++++++                            +++++++   +++ ++
           +++++     +++++++                       ++++++    +++  +++ +
         + +  +++++    ++++++++                 +++++++    ++++  +++++
           ++   +++++    ++++++++      1      +++++ ++   ++++  +++ ++
          + +++   +++ +  ++     +++    0    +++    +++ ++++  ++ ++++ +
          +++++++   ++++ ++    ++      1     +++   ++++++  +++  ++++
           ++++++++    ++++   +++      0      +++     +++++   ++++++
            +++ ++++++  +++  ++        0        ++ ++++++    +++++
            ++++  ++++++++++ ++        1       +++ ++ +    +  + ++
             +++++   + + ++++ +++++    0    ++++        ++++ ++
                +++   ++++++ ++ ++++   1   +++++  +++++++  +++++
               +++++     +++++ +++ ++  1  ++++++ +++++    +++++
                  +++++     +++++  ++  0  + + + ++     ++++
                   +++++++     ++  ++  0  +++ ++     ++++++
                       +++++ +++++ ++  0  +++ +  +++++++
                          ++++ +++++   1   +++++ +++
                             ++  ++         +   ++

             ____ _    ____ ____ _  _    ____ ____ ___  ____ ____
             |    |    |___ |__| |\ |    |    |  | |  \ |___ |__/
             |___ |___ |___ |  | | \|    |___ |__| |__/ |___ |  \

Traceback (most recent call last):
  File "C:\Users\rkowa\Desktop\geo\cleancoder\Clean-Coder-AI\single_task_coder.py", line 9, in <module>
    from src.agents.researcher_agent import Researcher
  File "C:\Users\rkowa\Desktop\geo\cleancoder\Clean-Coder-AI\src\agents\researcher_agent.py", line 6, in <module>
    from src.tools.tools_coder_pipeline import (
  File "C:\Users\rkowa\Desktop\geo\cleancoder\Clean-Coder-AI\src\tools\tools_coder_pipeline.py", line 8, in <module>        
    from src.utilities.user_input import user_input
  File "C:\Users\rkowa\Desktop\geo\cleancoder\Clean-Coder-AI\src\utilities\user_input.py", line 7, in <module>
    recorder = VoiceRecorder()
               ^^^^^^^^^^^^^^^
  File "C:\Users\rkowa\Desktop\geo\cleancoder\Clean-Coder-AI\src\utilities\voice_utils.py", line 31, in __init__
    self.openai_client = OpenAI()
                         ^^^^^^^^
  File "C:\Users\rkowa\.virtualenvs\Clean-Coder-AI-NYAWSSKX\Lib\site-packages\openai\_client.py", line 123, in __init__     
    super().__init__(
  File "C:\Users\rkowa\.virtualenvs\Clean-Coder-AI-NYAWSSKX\Lib\site-packages\openai\_base_client.py", line 849, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rkowa\.virtualenvs\Clean-Coder-AI-NYAWSSKX\Lib\site-packages\openai\_base_client.py", line 747, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

**Comment by radekrepo** [comment]
The latest changes from dev have resolved the issue. I close it now
