### ISSUE TITLE
Getting stuck after planning phase: Provider returned error

### ISSUE THREAD

**Issue by lgricius** [Grigorij-Dudnik/Clean-Coder-AI#32]
Current config:
- Docker based
- Tested with Master and Dev
- Using OpenRouter

I went through multiple runs attempting to finish full flow but with no luck. Unable to move from planning to execution.

`The tasks are ordered logically within each epic, and epics themselves are in the correct order for implementation. Each task has detailed instructions and acceptance criteria in its description.

I believe we can now start the implementation phase by making this task list active:
I'm thinking... 🌑🌑🌒🌓🌔🌕🌕🌕
Exception happened: {'message': 'Provider returned error', 'code': 400, 'metadata': {'raw': '{"message":"messages.28.content: Conversation blocks and tool result blocks cannot be provided in the same turn."}', 'provider_name': 'Amazon Bedrock'}} with llm: ChatOpenAI. Switching to next LLM if available...
Can not receive response from any llm
`

Can it be an issue with OpenRouter rotating LLMs in case of failure?

![image](https://github.com/user-attachments/assets/113c3b24-e48c-46c9-ab0e-1e3972eeebba)

**Comment by lgricius** [comment]
next run leads to nowhere: 
![image](https://github.com/user-attachments/assets/2d7d45fe-1aab-48e8-ba18-bd55e618c47a)

**Comment by Grigorij-Dudnik** [comment]
Hey, thank you for finding and reporting a bug.

I think I found the reason. Give me a while and it will be solved.

**Comment by Grigorij-Dudnik** [comment]
@lgricius Solved. Please update Clean Coder from "dev" branch and remove "manager_messages.json" in .clean_coder catalog in your working project directory to clean Manager's memory.

Problem was that langchain wasn't able to parse Openrouter's tool calls when tool has no arguments. I added dummy argument to "finish_project_planning" tool as walkaround.

**Comment by Grigorij-Dudnik** [comment]
@lgricius I see. Thanks for another bug finding. Working on it.

**Comment by Grigorij-Dudnik** [comment]
@lgricius Succesfully solved. Please update from branch "dev" and again remove old manager messages.

**Comment by lgricius** [comment]
I deleted old messages. Started Docker w/manager again.

😀 Hello! I'm Manager agent. Let's plan your project together!
? Choose an option: Start/continue planning my project (Default)
Let me analyze the current project state and planned tasks to determine the next steps.

Current project status:
....

Got error:

...
Let me check the project files to understand what's available.
Listing files in a directory...
{'directory': '.'}
Traceback (most recent call last):
  File "/Clean_Coder/manager.py", line 129, in <module>
    manager_instance.run()
  File "/Clean_Coder/manager.py", line 124, in run
    self.manager.invoke(inputs, {"recursion_limit": 1000})
  File "/usr/local/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1844, in invoke
    for chunk in self.stream(
  File "/usr/local/lib/python3.10/site-packages/langgraph/pregel/__init__.py", line 1573, in stream
    for _ in runner.tick(
  File "/usr/local/lib/python3.10/site-packages/langgraph/pregel/runner.py", line 104, in tick
    run_with_retry(t, retry_policy, writer=writer)
  File "/usr/local/lib/python3.10/site-packages/langgraph/pregel/retry.py", line 40, in run_with_retry
    task.proc.invoke(task.input, config)
  File "/usr/local/lib/python3.10/site-packages/langgraph/utils/runnable.py", line 410, in invoke
    input = context.run(step.invoke, input, config, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/langgraph/utils/runnable.py", line 184, in invoke
    ret = context.run(self.func, input, **kwargs)
  File "/Clean_Coder/manager.py", line 60, in call_model_manager
    state = actualize_tasks_list_and_progress_description(state)
  File "/Clean_Coder/src/utilities/manager_utils.py", line 251, in actualize_tasks_list_and_progress_description
    project_tasks = get_project_tasks()
NameError: name 'get_project_tasks' is not defined. Did you mean: 'parse_project_tasks'?

**Comment by Grigorij-Dudnik** [comment]
Oh, there something fresh bug related to new changes I implemented yesterday on dev. Thanks for pointing and working on it. In meanwhile please switch to master branch; release 0.3.0 have solved previous errors and should not have that new one.
